extends:
  - "@commitlint/config-conventional"
rules:
  body-max-line-length: [0, always]
  footer-max-line-length: [0, always]
  header-case: ['lower-case', always]
  scope-case: ['lower-case', always]
  subject-case: ['lower-case', always]
