branches:
  - main

env:
  HUSKY: 0

plugins:
  - "@semantic-release/commit-analyzer"
  - 
    - "@semantic-release/changelog"
    - changelogFile: 'docs/changelog.md'
  - "@semantic-release/release-notes-generator"
  - 
    - "@semantic-release/exec"
    - prepareCmd: "cp README.md ./src/Example/README.md && dotnet pack ./src/Example/Example.csproj -o ./publish"
  -
    - "@droidsolutions-oss/semantic-release-update-file"
    - files:
      - type: xml
        path:
        - "src/Example/Example.csproj"
        replacements:
        - key: Version
          value: ${nextRelease.version}
  -
    - "@semantic-release/git"
    - assets:
      - path: readme.md
        label: readme
      - path: docs/changelog.md
        label: changelog
      - path: publish/Example.${nextRelease.version}.nupkg
        label: nuget-package
    