branches:
  - main

env:
  HUSKY: 0
  HUSKY_SKIP_INSTALL: 1

plugins:
  - "@semantic-release/commit-analyzer"
  - 
    - "@semantic-release/changelog"
    - changelogFile: 'docs/CHANGELOG.md'
  - "@semantic-release/release-notes-generator"
  - 
    - "@semantic-release/exec"
    - prepareCmd: "dotnet pack ./src/Example/Example.csproj -o ./publish"
  -
    - "@droidsolutions-oss/semantic-release-update-file"
    - files:
      - type: xml
        path:
        - "src/Example/Example.csproj"
        replacements:
        - key: Version
          value: ${nextRelease.version}
  -
    - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} [skip ci]"
      assets:
      - docs/CHANGELOG.md
      - src/Example/Example.csproj
  
