name: Service Release & Deploy

# this wouldn't really be where we run it, but is the best place to test
on: 
  push:
    branches:
      - '*'

env:
  MAJOR_VERSION: '19700101'
  MINOR_VERSION: '1'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set env
        run: |
          echo "MAJOR_VERSION=$(date +%Y%m%d).${{ github.run_number }}" >> $GITHUB_ENV
          echo "MINOR_VERSION=$(($(git tag -l '$(date +%Y%m%d))*' | wc -l)+1)) >> $GITHUB_ENV"

      - name: test env
        run: echo ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}

