name: Service Release & Deploy

# this wouldn't really be where we run it, but is the best place to test
on: 
  push:
    branches:
      - '*'

env:
    VERSION_REFERENCE: unknown

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
        - name: tag last commit
          run: |
            echo VERSION_REFERENCE=$(date +%Y%m%d).${GITHUB_RUN_NUMBER} >> $GITHUB_ENV
            echo ${VERSION_REFERENCE}

