name: Release

on: 
  push:
    branches:
      - main

permissions:
  contents: read

env:
  USER_NAME: cduggan-reapit
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_FEED: https://nuget.pkg.github.com/cduggan-reapit/index.json
  NUGET_FEED_NAME: github

jobs:
  prepare-release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: install dependencies
        run: npm ci
      
      # Cut a new version if necessary
      - name: release
        id: semrel
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      
      # Publish the new version if everything has worked so far
      - name: publish to nuget feed
        if: success()
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet pack ./src/Example/Example.csproj -o ./nuget
          dotnet nuget add source ${NUGET_FEED} --name ${NUGET_FEED_NAME} --username ${USER_NAME} --password ${GITHUB_TOKEN}
          dotnet nuget list source
  